### ISSUE TITLE
Not work in local network

### ISSUE THREAD

**Issue by ZhouHansen** [geut/caracara#12]
I launched caracara on two laptops in the same local network, `192.168.0.9:3000/` and `192.168.0.8:3000/`, I share the public key of `192.168.0.9` to `192.168.0.8`: `http://192.168.0.8:3000/#/9502b972e277420887c55bb0890854e98c3d214004fa9f4d3538f509d954cf95`. Then I modify the editor of `192.168.0.9`, `192.168.0.8` does not change.

Both using localhost:3000 does not work too.

https://caracara.hashbase.io/ works well.

**Comment by nkint** [comment]
Hi! caracara.hashbase.io does not work right now.. any hint?

**Comment by dpaez** [comment]
Hello all! 👋 

@ZhouHansen mmm 🤔 that problem is a bit odd since caracara is working for you as you said. My guess is that there is some kind connection issue involving websockets/webrtc but caracara works and both are using the same config for the signalhub. Is there any message on the console? or in the network tab?

@nkint that is weird. hashbase does not give much info about what is going on, I've just tried to enter and it is working fine.

**Comment by dpaez** [comment]
hi all @ZhouHansen @nkint,

Are you still having troubles accessing the app? If so, can you share some logging information, you can get this data by taking a look into the console and also check the network panel. Otherwise I'm going to close this issue due to inactivity.

**Comment by nkint** [comment]
it is ok to me!

**Comment by nkint** [comment]
The issue can be closed, @ZhouHansen  ?

**Comment by ZhouHansen** [comment]
Oh, I am busy now, I will check it when I have time.
